version: '2'
services:
  adminer:
    image: 'adminer'
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: password
    links:
      - db:db

  db:
    image: 'mysql:8.0.30'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../data/db:/var/lib/mysql
      - ../initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - 3306:3306

  bot:
    build:
      context: ../bot
      dockerfile: dev.dockerfile
    volumes:
      - ../bot:/app # mount bot src
      - /app/node_modules # preserve node modules
    command: npm run dev
    depends_on:
      - db
    env_file:
      - ../.env
    environment:
      DATABASE_URL: mysql://root:password@db:3306/bot
