version: '2'
services:
  adminer:
    image: 'adminer'
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: password
    links:
      - db:db
      - migrate-db:migrate-db

  db:
    image: 'mysql:8.0.30'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../data/dev/db:/var/lib/mysql
      - ../initdb:/docker-entrypoint-initdb.d:ro

  migrate-db:
    image: 'mysql:8.0.30'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../data/dev-migrations/db:/var/lib/mysql
      - ../initdb:/docker-entrypoint-initdb.d:ro

  migrator:
    build:
      context: ../backend
      dockerfile: dev.dockerfile
    volumes:
      - ../backend/src:/app/src:ro
      - /app/node_modules
    command: |
      /bin/sh -c "
      echo 'Started; waiting for DB'
      while ! nc -z db 3306
        do sleep 1
      done
      npx nodemon --legacy-watch --watch src/migrations -e ts --exec \"npm run migrate\" --polling-interval 5000"
    depends_on:
      - migrate-db
    environment:
      DATABASE_URL: mysql://root:password@migrate-db:3306/networkbot
      MIGRATE_DATABASE_URL: mysql://root:password@migrate-db:3306/networkbot

  backend:
    build:
      context: ../backend
      dockerfile: dev.dockerfile
    volumes:
      - ../backend/src:/app/src:ro
      - /app/node_modules
    command: |
      /bin/sh -c "
      echo 'Started; waiting for DB'
      while ! nc -z db 3306 
        do sleep 1
      done
      npm run dev"
    depends_on:
      - db
      - migrate-db
      - migrator
    env_file:
      - ../.env
    environment:
      DATABASE_URL: mysql://root:password@db:3306/networkbot
      MIGRATE_DATABASE_URL: mysql://root:password@migrate-db:3306/networkbot
