version: '2'
services:
  adminer:
    image: 'adminer'
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: password
    links:
      - db:db

  db:
    image: 'mysql:8.0.30'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../data/prod/db:/var/lib/mysql
      - ../initdb:/docker-entrypoint-initdb.d:ro

  migrator:
    build:
      context: ../bot
      dockerfile: prod.dockerfile
    command: npm run migrate
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:password@db:3306/bot
      MIGRATE_DATABASE_URL: mysql://root:password@db:3306/bot

  bot:
    build:
      context: ../bot
      dockerfile: prod.dockerfile
    depends_on:
      - db
      - migrator
    env_file:
      - ../.env
    environment:
      DATABASE_URL: mysql://root:password@db:3306/bot
      MIGRATE_DATABASE_URL: mysql://root:password@db:3307/bot
