version: '2'
services:
  adminer:
    image: 'adminer'
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: password
    links:
      - db:db

  test-db:
    image: 'mysql:8.0.30'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/test-db:/var/lib/mysql

  db:
    image: 'mysql:8.0.30'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - 3306:3306

  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PASS=password
      - DB_PORT=3066
